---
title: "geoms"
output: html_notebook
---

```{r}
library(tidyverse); library(grid)
```

```{r geom_point, eval=FALSE}
#https://github.com/tidyverse/ggplot2/blob/master/R/geom-point.r
geom_point <- function(mapping = NULL, data = NULL,
                       stat = "identity", position = "identity",
                       ...,
                       na.rm = FALSE,
                       show.legend = NA,
                       inherit.aes = TRUE) {
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomPoint,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      na.rm = na.rm,
      ...
    )
  )
}
GeomPoint <- ggproto("GeomPoint", Geom,
  required_aes = c("x", "y"),
  non_missing_aes = c("size", "shape", "colour"),
  default_aes = aes(
    shape = 19, colour = "black", size = 1.5, fill = NA,
    alpha = NA, stroke = 0.5
  ),

  draw_panel = function(data, panel_params, coord, na.rm = FALSE) {
    coords <- coord$transform(data, panel_params)
    ggname("geom_point",
      pointsGrob(
        coords$x, coords$y,
        pch = coords$shape,
        gp = gpar(
          col = alpha(coords$colour, coords$alpha),
          fill = alpha(coords$fill, coords$alpha),
          # Stroke is added around the outside of the point
          fontsize = coords$size * .pt + coords$stroke * .stroke / 2,
          lwd = coords$stroke * .stroke / 2
        )
      )
    )
  },

  draw_key = draw_key_point
)
```

```{r geom_segment, eval=FALSE}
#https://github.com/tidyverse/ggplot2/blob/master/R/geom-segment.r
geom_segment <- function(mapping = NULL, data = NULL,
                         stat = "identity", position = "identity",
                         ...,
                         arrow = NULL,
                         lineend = "butt",
                         linejoin = "round",
                         na.rm = FALSE,
                         show.legend = NA,
                         inherit.aes = TRUE) {
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomSegment,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      arrow = arrow,
      lineend = lineend,
      linejoin = linejoin,
      na.rm = na.rm,
      ...
    )
  )
}

#' @rdname ggplot2-ggproto
#' @format NULL
#' @usage NULL
#' @export
GeomSegment <- ggproto("GeomSegment", Geom,
  required_aes = c("x", "y", "xend", "yend"),
  non_missing_aes = c("linetype", "size", "shape"),
  default_aes = aes(colour = "black", size = 0.5, linetype = 1, alpha = NA),

  draw_panel = function(data, panel_params, coord, arrow = NULL,
                        lineend = "butt", linejoin = "round", na.rm = FALSE) {

    data <- remove_missing(data, na.rm = na.rm,
      c("x", "y", "xend", "yend", "linetype", "size", "shape"),
      name = "geom_segment")
    if (empty(data)) return(zeroGrob())

    if (coord$is_linear()) {
      coord <- coord$transform(data, panel_params)
      return(segmentsGrob(coord$x, coord$y, coord$xend, coord$yend,
        default.units = "native",
        gp = gpar(
          col = alpha(coord$colour, coord$alpha),
          fill = alpha(coord$colour, coord$alpha),
          lwd = coord$size * .pt,
          lty = coord$linetype,
          lineend = lineend,
          linejoin = linejoin
        ),
        arrow = arrow
      ))
    }

    data$group <- 1:nrow(data)
    starts <- subset(data, select = c(-xend, -yend))
    ends <- plyr::rename(subset(data, select = c(-x, -y)), c("xend" = "x", "yend" = "y"),
      warn_missing = FALSE)

    pieces <- rbind(starts, ends)
    pieces <- pieces[order(pieces$group),]

    GeomPath$draw_panel(pieces, panel_params, coord, arrow = arrow,
      lineend = lineend)
  },

  draw_key = draw_key_path
)
```

```{r geom_text, eval=FALSE}
#https://github.com/tidyverse/ggplot2/blob/master/R/geom-text.r
geom_text <- function(mapping = NULL, data = NULL,
                      stat = "identity", position = "identity",
                      ...,
                      parse = FALSE,
                      nudge_x = 0,
                      nudge_y = 0,
                      check_overlap = FALSE,
                      na.rm = FALSE,
                      show.legend = NA,
                      inherit.aes = TRUE)
{
  if (!missing(nudge_x) || !missing(nudge_y)) {
    if (!missing(position)) {
      stop("Specify either `position` or `nudge_x`/`nudge_y`", call. = FALSE)
    }

    position <- position_nudge(nudge_x, nudge_y)
  }

  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomText,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      parse = parse,
      check_overlap = check_overlap,
      na.rm = na.rm,
      ...
    )
  )
}


#' @rdname ggplot2-ggproto
#' @format NULL
#' @usage NULL
#' @export
GeomText <- ggproto("GeomText", Geom,
  required_aes = c("x", "y", "label"),

  default_aes = aes(
    colour = "black", size = 3.88, angle = 0, hjust = 0.5,
    vjust = 0.5, alpha = NA, family = "", fontface = 1, lineheight = 1.2
  ),

  draw_panel = function(data, panel_params, coord, parse = FALSE,
                        na.rm = FALSE, check_overlap = FALSE) {
    lab <- data$label
    if (parse) {
      lab <- parse(text = as.character(lab))
    }

    data <- coord$transform(data, panel_params)
    if (is.character(data$vjust)) {
      data$vjust <- compute_just(data$vjust, data$y)
    }
    if (is.character(data$hjust)) {
      data$hjust <- compute_just(data$hjust, data$x)
    }

    textGrob(
      lab,
      data$x, data$y, default.units = "native",
      hjust = data$hjust, vjust = data$vjust,
      rot = data$angle,
      gp = gpar(
        col = alpha(data$colour, data$alpha),
        fontsize = data$size * .pt,
        fontfamily = data$family,
        fontface = data$fontface,
        lineheight = data$lineheight
      ),
      check.overlap = check_overlap
    )
  },

  draw_key = draw_key_text
)
```

```{r geom_timeline}
#earthquake timeline geom based on geom_point
geom_timeline <- function(mapping = NULL, data = NULL,
                       stat = "identity", position = "identity",
                       xmin = NA, xmax = NA, #new filter parameters
                       ...,
                       na.rm = FALSE,
                       show.legend = NA,
                       inherit.aes = TRUE) {
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomTimeline,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      xmin=xmin, xmax=xmax,
      na.rm = na.rm,
      ...
    )
  )
}
GeomTimeline <- ggproto("GeomPoint", Geom,
  required_aes = c("x"),
  non_missing_aes = c("size", "shape", "colour"),
  default_aes = aes(
    shape = 19, colour = "black", size = 1.5, fill = NA,
    alpha = NA, stroke = 0.5
  ),

  draw_panel = function(data, panel_params, coord, na.rm = FALSE, xmin=NA, xmax=NA) {
    date_prep <- function(y, m, d){
      #for now as.date doesn't process negative years so workaround
      if (y < 0){yr <- y * -1} else {yr <- y}
      ymd <- as.Date(paste0(yr, "/", m, "/", d), format='%Y/%m/%d')
      if (y < 0){
        lubridate::year(ymd) <- y
      }
      return(as.numeric(ymd))
    }
    #filter dates by years if xmin or xmax passed
    if(!is.na(xmin)){
      ymd_min <- date_prep(xmin,1,1) 
      data <- data %>%
        filter(x >= ymd_min)
    }
    if(!is.na(xmax)){
      ymd_max <- date_prep(xmax,12,31) 
      data <- data %>%
        filter(x <= ymd_max)
    }
    if (is.null(data$x)) return(zeroGrob())

    coords <- coord$transform(data, panel_params)
    seg_grob <- segmentsGrob(min(coords$x), coords$y, max(coords$x), coords$y,                             
        default.units = "native",
        gp = gpar(col = "#636363", fill = "#636363", lwd = 1, lty = 1) #line segment grey
      )     
    #grob code below is adapted from geom_point (github tidyverse\ggplot2)
    dots_grob <- pointsGrob(
        coords$x, coords$y,
        pch = coords$shape,
        gp = gpar(
          col = alpha(coords$colour, coords$alpha),
          fill = alpha(coords$fill, coords$alpha),
          fontsize = coords$size * .pt + coords$stroke * .stroke / 2,
          lwd = coords$stroke * .stroke / 2
        )
      )
    gTree(children = gList(seg_grob, dots_grob))
  },

  draw_key = draw_key_point
)
```

```{r geom_timeline_label}
#label geom partners with geom_timeline
geom_timeline_label <- function(mapping = NULL, data = NULL,
                       stat = "identity", position = "identity",
                       xmin = NA, xmax = NA, n_max = NA,#new filter parameters
                       ...,
                       check_overlap = FALSE,
                       na.rm = FALSE,
                       show.legend = NA,
                       inherit.aes = TRUE) {
  layer(
    data = data,
    mapping = mapping,
    stat = stat,
    geom = GeomTimelineLabel,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      xmin=xmin, xmax=xmax, n_max = n_max,
      check_overlap = check_overlap,
      na.rm = na.rm,
      ...
    )
  )
}
GeomTimelineLabel <- ggproto("GeomText", Geom,
  required_aes = c("x", "label"),
  default_aes = aes(
    colour = "black", size = 3.88, angle = 0, hjust = 0.5,
    vjust = 0.5, alpha = NA, family = "", fontface = 1, lineheight = 1.2
  ),

  draw_panel = function(data, panel_params, coord, na.rm = FALSE, check_overlap = FALSE, xmin=NA, xmax=NA, n_max=NA) {
    date_prep <- function(y, m, d){
      #for now as.date doesn't process negative years so workaround
      if (y < 0){yr <- y * -1} else {yr <- y}
      ymd <- as.Date(paste0(yr, "/", m, "/", d), format='%Y/%m/%d')
      if (y < 0){
        lubridate::year(ymd) <- y
      }
      return(as.numeric(ymd))
    }
    #filter dates by years if xmin or xmax passed
    if(!is.na(xmin)){
      ymd_min <- date_prep(xmin,1,1) 
      data <- data %>%
        filter(x >= ymd_min)
    }
    if(!is.na(xmax)){
      ymd_max <- date_prep(xmax,12,31) 
      data <- data %>%
        filter(x <= ymd_max)
    }
    if(!is.na(n_max)){ #filter max items by size
    data <- data %>%
      group_by(group) %>%
      top_n(n_max, size) %>%
      ungroup()
    }
    if (is.null(data$x)) return(zeroGrob())
    
    coords <- coord$transform(data, panel_params)
    seg_grob <- segmentsGrob(coords$x, coords$y, coords$x, (coords$y*1.2),                             
        default.units = "native",
        gp = gpar(col = "#636363", fill = "#636363", lwd = 0.8, lty = 1) #line segment grey
      )
    txt_grob <- textGrob(
      data$label,
      coords$x, coords$y*1.2, default.units = "native",
      just="right",
      hjust = 0, vjust = 0.6, #left justified & raised slightly above center
      rot = 45,
      gp = gpar(
        col = "black",
        fontsize=12,
        fontface = data$fontface,
        lineheight = data$lineheight
      ),
      check.overlap = TRUE
    )
    gTree(children = gList(seg_grob, txt_grob))
  },

  draw_key = draw_key_text
)
```

```{r, eval=FALSE}
df.clean <- readRDS("dfclean.rds")
```

```{r, fig.height=6, fig.width=12}
df.clean %>%
  filter(COUNTRY %in% c("CHINA", "INDONESIA", "JAPAN")) %>%
  filter(lubridate::year(DATE) > 2000) %>%
#  filter(lubridate::year(DATE) > 2014) %>%
  arrange(desc(COUNTRY)) %>%
  mutate(COUNTRY = factor(COUNTRY),
         TOTAL_DAMAGE_MILLIONS_DOLLARS = ifelse(is.na(TOTAL_DAMAGE_MILLIONS_DOLLARS), 0, as.numeric(TOTAL_DAMAGE_MILLIONS_DOLLARS)),
         EQ_MAG_MB = ifelse(is.na(EQ_MAG_MB), 0, as.numeric(EQ_MAG_MB)),
         Magnitude = ifelse(is.na(EQ_PRIMARY), 0, as.numeric(EQ_PRIMARY)),
         TOTAL_DEATHS = ifelse(is.na(TOTAL_DEATHS), 0, as.numeric(TOTAL_DEATHS))) %>%
#  select(TOTAL_DEATHS, TOTAL_DAMAGE_MILLIONS_DOLLARS, EQ_MAG_MB) 
  ggplot(aes(x=DATE, y=COUNTRY, colour=Magnitude, alpha=TOTAL_DEATHS, size=Magnitude, label=LOCATION_NAME)) +
#  geom_timeline(xmin=-200, xmax=1700) + 
  geom_timeline() + 
  geom_timeline_label(n_max = 3) +
  guides(alpha = FALSE, colour=FALSE) +
  scale_x_date(date_labels = "%Y") 
```
```{r, fig.height=6, fig.width=12}
df.clean %>%
  filter(COUNTRY %in% c("USA")) %>%
  filter(lubridate::year(DATE) > 2000) %>%
  arrange(desc(COUNTRY)) %>%
  mutate(COUNTRY = factor(COUNTRY),
         TOTAL_DAMAGE_MILLIONS_DOLLARS = ifelse(is.na(TOTAL_DAMAGE_MILLIONS_DOLLARS), 0, as.numeric(TOTAL_DAMAGE_MILLIONS_DOLLARS)),
         EQ_MAG_MB = ifelse(is.na(EQ_MAG_MB), 0, as.numeric(EQ_MAG_MB)),
         Magnitude = ifelse(is.na(EQ_PRIMARY), 0, as.numeric(EQ_PRIMARY)),
         TOTAL_DEATHS = ifelse(is.na(TOTAL_DEATHS), 0, as.numeric(TOTAL_DEATHS))) %>%
#  select(TOTAL_DEATHS, TOTAL_DAMAGE_MILLIONS_DOLLARS, EQ_MAG_MB) 
  ggplot(aes(x=DATE, y=COUNTRY, colour=Magnitude, alpha=TOTAL_DEATHS, size=Magnitude, label=LOCATION_NAME)) +
#  geom_timeline(xmin=-200, xmax=1700) + 
  geom_timeline() + 
  geom_timeline_label(n_max = 6) +
  guides(alpha = FALSE, colour=FALSE) +
  scale_x_date(date_labels = "%Y") 
```

```{r, fig.height=4, fig.width=12}
df.clean %>%
  filter(COUNTRY %in% c("BRAZIL")) %>%
  mutate(COUNTRY = factor(COUNTRY),
         TOTAL_DAMAGE_MILLIONS_DOLLARS = ifelse(is.na(TOTAL_DAMAGE_MILLIONS_DOLLARS), 0, as.numeric(TOTAL_DAMAGE_MILLIONS_DOLLARS)),
         EQ_MAG_MB = ifelse(is.na(EQ_MAG_MB), 0, as.numeric(EQ_MAG_MB)), 
         Magnitude = ifelse(is.na(EQ_PRIMARY), 0, as.numeric(EQ_PRIMARY)),
         TOTAL_DEATHS = ifelse(is.na(TOTAL_DEATHS), 0, as.numeric(TOTAL_DEATHS))) %>%
#  select(TOTAL_DEATHS, TOTAL_DAMAGE_MILLIONS_DOLLARS, EQ_MAG_MB) 
  ggplot(aes(x=DATE, y=COUNTRY, colour=Magnitude, alpha=Magnitude, size=Magnitude, label=LOCATION_NAME)) +
  geom_timeline()+#xmin=2000, xmax=2008)+#xmin=-800, xmax=1400) + 
  geom_timeline_label(n_max = 2) +
  guides(alpha = FALSE, colour=FALSE) +
  scale_x_date(date_labels = "%Y") 
```


